# IO analysis

* https://rdrr.io/cran/ioanalysis/
* https://www.cso.ie/en/statistics/nationalaccounts/supplyandusetablesforireland/
* https://www.wider.unu.edu/database/2013-social-accounting-matrix-zimbabwe
* http://www.real.illinois.edu/pyio/
* https://cran.r-project.org/web/packages/ioanalysis/ioanalysis.pdf
* https://www.youtube.com/watch?v=DTEtumQ4DW8
* https://peter-puszko.medium.com/solving-leontiefs-input-output-model-in-python-a0a29455b2d8

In [13]:
import pandas as pd
import seaborn as sns

In [9]:
X=pd.read_csv('WP2018-139-Data-for-a-2013-Zimbabwe-SAM.csv',index_col=0)

In [16]:
X.fillna(0)

,alagr,asagr,afore,afish,amcoa,amnfm,amoth,afood,atobm,atext,...,hhrur,hhurb,gov,atax,stax,mtax,dtax,s-i,dstk,row
alagr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
asagr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
afore,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
afish,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
amcoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mtax,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
dtax,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,228,433,0,0.0,0,0.0,0,0,0.0,0
s-i,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"-1,450","-2,307",398,0.0,0,0.0,0,0,0.0,"3,889"
dstk,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0,5,0.0,0
row,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,20,801,0.0,0,0.0,0,0,0.0,0

In [27]:
print(X.sum())

alagr     1362.0
asagr     1048.0
afore      141.0
afish        0.0
amcoa      655.0
           ...
flabus    1478.0
fmix       831.0
atax       188.0
mtax       362.0
dstk         5.0
Length: 81, dtype: float64

In [26]:
print(X.sum(1))

alagr    1364.0
asagr    1048.0
afore     141.0
afish       1.0
amcoa     657.0
          ...
mtax      147.0
dtax        0.0
s-i         0.0
dstk        0.0
row      1947.0
Length: 100, dtype: float64

In [25]:
list(X.sum())

[1362.0,
 1048.0,
 141.0,
 0.0,
 655.0,
 947.0,
 93.0,
 914.0,
 474.0,
 43.0,
 29.0,
 31.0,
 100.0,
 105.0,
 46.0,
 270.0,
 75.0,
 11.0,
 80.0,
 59.0,
 111.0,
 323.0,
 32.0,
 80.0,
 176.0,
 750.0,
 710.0,
 1249.0,
 956.0,
 1446.0,
 3041.0,
 1060.0,
 263.0,
 55.0,
 636.0,
 1296.0,
 412.0,
 103.0,
 190.0,
 100.0,
 140.0,
 185.0,
 196.0,
 226.0,
 16.0,
 61.0,
 160.0,
 1.0,
 95.0,
 506.0,
 788.0,
 192.0,
 414.0,
 131.0,
 156.0,
 235.0,
 94.0,
 158.0,
 99.0,
 141.0,
 242.0,
 24.0,
 142.0,
 585.0,
 257.0,
 328.0,
 804.0,
 278.0,
 492.0,
 454.0,
 707.0,
 1284.0,
 263.0,
 57.0,
 498.0,
 1016.0,
 1478.0,
 831.0,
 188.0,
 362.0,
 5.0]

In [17]:
sns.heatmap(X.fillna(0))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''